name: tags
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dio: ^5.1.1
  get_it: ^7.2.0
  injectable: ^2.1.1
  clipboard: ^0.1.3
  flutter_dotenv: ^5.0.2
  flutter_file_downloader: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - .env
